#
# Copyright (C) 2011, deadcafe.beef@gmail.com
# All rights reserved.
#

TARGET = mqueue.lib

SRCS	=		\
	mqueue.c

TOPDIR = ../..
LIBS =
COPTFLAGS = -O0
CFLAGS_EXTRA =
LDFLAGS_EXTRA =

-include $(TOPDIR)/makefiles/Makefile.lib

