#
# Copyright (C) 2011, deadcafe.beef@gmail.com
# All rights reserved.
#

TARGET = cmd.lib

SRCS	=		\
	command.c	\
	console.c

TOPDIR = ../..
LIBS = -levent
COPTFLAGS = -O0
CFLAGS_EXTRA = 

-include $(TOPDIR)/makefiles/Makefile.lib
