#
# Copyright (C) 2011, deadcafe.beef@gmail.com
# All rights reserved.
#

TARGET = slaver.lib

SRCS	=		\
	slaver.c

TOPDIR = ../..
LIBS = -levent -lpthread
COPTFLAGS = -O0
CFLAGS_EXTRA = -pthread
LDFLAGS_EXTRA = -pthread

-include $(TOPDIR)/makefiles/Makefile.lib

