#
# Copyright (C) 2011, deadcafe.beef@gmail.com
# All rights reserved.
#

TARGET = fstream.lib

SRCS	=		\
	fstream.c	\
	socket.c

TOPDIR = ../..
LIBS = -levent
COPTFLAGS = -O0
CFLAGS_EXTRA = 

-include $(TOPDIR)/makefiles/Makefile.lib

