#
# Copyright (C) 2011, deadcafe.beef@gmail.com
# All rights reserved.
#

TARGET = utils.lib

SRCS	=	\
	log.c

TOPDIR = ../..
LIBS =
COPTFLAGS = -O0
CFLAGS_EXTRA = 

-include $(TOPDIR)/makefiles/Makefile.lib

