#
# Copyright (C) 2011, deadcafe.beef@gmail.com
# All rights reserved.
#

all:	build.console build.daemon

build.console:
	$(MAKE) -f Makefile.console

build.daemon:
	$(MAKE) -f Makefile.daemon


clean:	clean.console clean.daemon

clean.console:
	$(MAKE) -f Makefile.console clean

clean.daemon:
	$(MAKE) -f Makefile.daemon clean

.MAKE:
