/*
 * Copyright (C) 2011, deadcafe.beef@gmail.com
 * All rights reserved.
 */

#ifndef	_JD_IKEV2_IANA_H_
#define	_JD_IKEV2_IANA_H_

/*
 * Exchange Type
 */
#define	IKEV2_IANA_EXCHG_IKE_SA_INIT
#define	IKEV2_IANA_EXCHG_IKE_AUTH
#define	IKEV2_IANA_EXCHG_CREATE_CHILD_SA
#define	IKEV2_IANA_EXCHG_INFORMATIONAL
#define	IKEV2_IANA_EXCHG_IKE_SESSION_RESUME


/*
 * Payload Type
 */
#define	IKEV2_IANA_PAYLOAD_NONE
#define	IKEV2_IANA_PAYLOAD_SA
#define	IKEV2_IANA_PAYLOAD_KE
#define	IKEV2_IANA_PAYLOAD_IDi
#define	IKEV2_IANA_PAYLOAD_IDr
#define	IKEV2_IANA_PAYLOAD_CERT
#define	IKEV2_IANA_PAYLOAD_CERTREQ
#define	IKEV2_IANA_PAYLOAD_AUTH
#define	IKEV2_IANA_PAYLOAD_Ni
#define	IKEV2_IANA_PAYLOAD_Nr
#define	IKEV2_IANA_PAYLOAD_N
#define	IKEV2_IANA_PAYLOAD_V
#define	IKEV2_IANA_PAYLOAD_TSi
#define	IKEV2_IANA_PAYLOAD_TSr
#define	IKEV2_IANA_PAYLOAD_SK
#define	IKEV2_IANA_PAYLOAD_CP
#define	IKEV2_IANA_PAYLOAD_EAP


/*
 * Transform Type
 */
#define	IKEV2_IANA_TRANSFORM_ENCR
#define	IKEV2_IANA_TRANSFORM_PRF
#define	IKEV2_IANA_TRANSFORM_INTEG
#define	IKEV2_IANA_TRANSFORM_DH
#define	IKEV2_IANA_TRANSFORM_ESN

/*
 * Transform Attribute Type
 */
#define	IKEV2_IANA_TRANSFORM_ATTR_KEYLEN	/* bit */

/*
 * Encryption Algorithm Transform IDs
 */
#define	IKEV2_IANA_ENCR_DES_IV64	1
#define	IKEV2_IANA_ENCR_DES		2
#define	IKEV2_IANA_ENCR_3DES		3
#define	IKEV2_IANA_ENCR_RC5		4
#define	IKEV2_IANA_ENCR_IDEA		5
#define	IKEV2_IANA_ENCR_CAST		6
#define	IKEV2_IANA_ENCR_BLOWFISH	7
#define	IKEV2_IANA_ENCR_3IDEA		8
#define	IKEV2_IANA_ENCR_DES_IV32	9
#define	IKEV2_IANA_ENCR_NULL		11
#define	IKEV2_IANA_ENCR_AES_CBC		12
#define	IKEV2_IANA_ENCR_AES_CTR		13
#define	IKEV2_IANA_ENCR_AES_CCM_8	14
#define	IKEV2_IANA_ENCR_AES_CCM_12	15
#define	IKEV2_IANA_ENCR_AES_CCM_16	16
#define	IKEV2_IANA_AES_GCM_WITH_8_ICV	18
#define	IKEV2_IANA_AES_GCM_WITH_12_ICV	19
#define	IKEV2_IANA_AES_GCM_WITH_16_ICV	20
#define	IKEV2_IANA_ENCR_NULL_AUTH_AES_GMAC	21
#define	IKEV2_IANA_ENCR_CAMELLIA_CBC	23
#define	IKEV2_IANA_ENCR_CAMELLIA_CTR	24
#define	IKEV2_IANA_ENCR_CAMELLIA_CCM_WITH_8_ICV		25
#define	IKEV2_IANA_ENCR_CAMELLIA_CCM_WITH_12_ICV	26
#define	IKEV2_IANA_ENCR_CAMELLIA_CCM_WITH_16_ICV	27

/*
 * Pseudo-random Function Transform IDs
 */
#define	IKEV2_IANA_PRF_NULL		0	/* dummy */
#define	IKEV2_IANA_PRF_HMAC_MD5		1
#define	IKEV2_IANA_PRF_HMAC_SHA1	2
#define	IKEV2_IANA_PRF_HMAC_TIGER	3
#define	IKEV2_IANA_PRF_AES128_XCBC	4
#define	IKEV2_IANA_PRF_HMAC_SHA2_256	5
#define	IKEV2_IANA_PRF_HMAC_SHA2_384	6
#define	IKEV2_IANA_PRF_HMAC_SHA2_512	7
#define	IKEV2_IANA_PRF_AES128_CMAC	8


/*
 * Integrity Algorithm Transform IDs
 */
#define	IKEV2_IANA_AUTH_NONE		0
#define	IKEV2_IANA_AUTH_HMAC_MD5_96	1
#define	IKEV2_IANA_AUTH_HMAC_SHA1_96	2
#define	IKEV2_IANA_AUTH_DES_MAC		3
#define	IKEV2_IANA_AUTH_KPDK_MD5	4
#define	IKEV2_IANA_AUTH_AES_XCBC_96	5
#define	IKEV2_IANA_AUTH_HMAC_MD5_128	6
#define	IKEV2_IANA_AUTH_HMAC_SHA1_160	7
#define	IKEV2_IANA_AUTH_AES_CMAC_96	8
#define	IKEV2_IANA_AUTH_AES_128_GMAC	9
#define	IKEV2_IANA_AUTH_AES_192_GMAC	10
#define	IKEV2_IANA_AUTH_AES_256_GMAC	11
#define	IKEV2_IANA_AUTH_HMAC_SHA2_256_128	12
#define	IKEV2_IANA_AUTH_HMAC_SHA2_384_192	13
#define	IKEV2_IANA_AUTH_HMAC_SHA2_512_256	14

/*
 * Diffie-Hellman Group Transform IDs
 */
#define	IKEV2_IANA_DH_NONE		0
#define	IKEV2_IANA_DH_GROUP1		1
#define	IKEV2_IANA_DH_GROUP2		2
#define	IKEV2_IANA_DH_MODP_768	IKEV2_IANA_DH_GROUP1
#define	IKEV2_IANA_DH_MODP_1024	IKEV2_IANA_DH_GROUP2
#define	IKEV2_IANA_DH_MODP_1536		5
#define	IKEV2_IANA_DH_MODP_2048		14
#define	IKEV2_IANA_DH_MODP_3072		15
#define	IKEV2_IANA_DH_MODP_4096		16
#define	IKEV2_IANA_DH_MODP_6144		17
#define	IKEV2_IANA_DH_MODP_8192		18
#define	IKEV2_IANA_DH_ECP_256		19
#define	IKEV2_IANA_DH_ECP_384		20
#define	IKEV2_IANA_DH_ECP_521		21
#define	IKEV2_IANA_DH_MODP_1024_PRIME_160	22
#define	IKEV2_IANA_DH_MODP_2048_PRIME_224	23
#define	IKEV2_IANA_DH_MODP_2048_PRIME_256	24
#define	IKEV2_IANA_DH_ECP_192		25
#define	IKEV2_IANA_DH_ECP_224		26

#endif	/* !_JD_IKEV2_IANA_H_ */
